### ISSUE TITLE
JavaScript hide fails when using multiple @SHOW_BY_ROLES fields

### ISSUE THREAD

**Issue by steentje34** [redcapuzgent/redcap_shown_by_role#1]
When using multiple @SHOW_BY_ROLES fields, only the last @SHOW_BY_ROLES field in the project gets hidden for users who are not supposed to see the field. It seems that the issue is linked to following line.
https://github.com/denshade/redcap_shown_by_role/blob/99158a39d7510544481880cf8b49991063f4bd6c/ShowByRolesClass.php#L93

Adding a semicolon should solve the issue.
`echo 'UZG_hideaway.hideIt("' . $fieldToHide . '");'; `

**Comment by denshade** [comment]
Semicolon added.
