### ISSUE TITLE
Feature request: allow random order when using multiple action tags

### ISSUE THREAD

**Issue by steentje34** [redcapuzgent/redcap_shown_by_role#2]
Currently, @SHOW_BY_ROLES will not hide fields if multiple action tags are used, unless it is the first action tag. I think it would be aan enhancement if @SHOW_BY_ROLES could be in whatever position in the action tags field.

Alternatively, if this would be technically not feasible, I think the documentation should be updated to reflect this limitation.

**Comment by denshade** [comment]
This should be resolved in commit a26379a33cc9c2c8786028ae792ceacf17c549c5.
